import { planVersion } from './plan-version.js';
import firstPlan from './data/kings-edge-plan.json';
import secondPlan from './data/v2/kings-edge-plan.json';
import firstEnablingProjects from './data/enabling-projects.json';
import secondEnablingProjects from './data/v2/enabling-projects.json';
import firstStepDependencies from './data/step-dependencies.json';
import secondStepDependencies from './data/v2/step-dependencies.json';
import firstReconciliations from './data/shared-resource-reconciliations.json';
import secondReconciliations from './data/v2/shared-resource-reconciliations.json';
import firstStatus from './data/status.json';
import secondStatus from './data/v2/status.json';
import firstSharedResources from './data/shared-resources.json';
import secondSharedResources from './data/v2/shared-resources.json';
import firstProgrammeContexts from './data/project-programme-contexts.json';
import secondProgrammeContexts from './data/v2/project-programme-contexts.json';
import firstTheory from './data/theory-of-change.json';
import secondTheory from './data/v2/theory-of-change.json';
import { registeredDeliverableMap as firstDeliverables } from './data/deliverables/index.js';
import { registeredDeliverableMap as secondDeliverables } from './data/v2/deliverables/index.js';

const second = planVersion === 'v2';
export const plan = second ? secondPlan : firstPlan;
export const enablingProjects = second ? secondEnablingProjects : firstEnablingProjects;
export const stepDependencies = second ? secondStepDependencies : firstStepDependencies;
export const resourceReconciliations = second ? secondReconciliations : firstReconciliations;
export const status = second ? secondStatus : firstStatus;
export const sharedResources = second ? secondSharedResources : firstSharedResources;
export const programmeContexts = second ? secondProgrammeContexts : firstProgrammeContexts;
export const theoryOfChange = second ? secondTheory : firstTheory;
export const registeredDeliverableMap = second ? secondDeliverables : firstDeliverables;
